In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from my_functions import combokey_converter

%matplotlib inline
sns.set_style('whitegrid')
plt.rc('axes', titlesize = 14, titleweight = 'bold', labelweight = 'bold')

# <font color = green> I. Column Info </font>

#  Column info for crdc_1516 
<b><div class="alert alert-block alert-info"> Contains 111 Fields </b>

In [2]:
crdc_cols = pd.read_csv('../filtered_data/00_crdc_1516_initial_layout.csv')

In [3]:
with pd.option_context('display.max_colwidth', 150, 'display.max_rows', 125):
    display(crdc_cols.drop('Module', axis = 1).set_index('Field_Name'))

                                                                                                                             Field_Description
Field_Name
LEA_STATE                                                                                                          District State Abbreviation
LEA_STATE_NAME                                                                                                             District State Name
LEAID                                                                                               7 Digit LEAID District Identification Code
LEA_NAME                                                                                                                         District Name
SCHID                                                                                                       5 Digit School Identification Code
SCH_NAME                                                                                                                           School Name
COMBOKEY                                                         7 Digit LEAID District Identification Code+5 Digit School Identification Code
JJ                                    Juvenile Justice Facility: "Yes" indicates a long-term secure facility; "No" indicates not a JJ facility
SCH_GRADE_PS                                                                                          Grades with Students Enrolled: Preschool
SCH_GRADE_KG                                                                                       Grades with Students Enrolled: Kindergarten
SCH_GRADE_G01                                                                                           Grades with Students Enrolled: Grade 1
SCH_GRADE_G02                                                                                           Grades with Students Enrolled: Grade 2
SCH_GRADE_G03                                                                                           Grades with Students Enrolled: Grade 3
SCH_GRADE_G04                                                                                           Grades with Students Enrolled: Grade 4
SCH_GRADE_G05                                                                                           Grades with Students Enrolled: Grade 5
SCH_GRADE_G06                                                                                           Grades with Students Enrolled: Grade 6
SCH_GRADE_G07                                                                                           Grades with Students Enrolled: Grade 7
SCH_GRADE_G08                                                                                           Grades with Students Enrolled: Grade 8
SCH_GRADE_G09                                                                                           Grades with Students Enrolled: Grade 9
SCH_GRADE_G10                                                                                          Grades with Students Enrolled: Grade 10
SCH_GRADE_G11                                                                                          Grades with Students Enrolled: Grade 11
SCH_GRADE_G12                                                                                          Grades with Students Enrolled: Grade 12
SCH_GRADE_UG                                                                                           Grades with Students Enrolled: Ungraded
SCH_UGDETAIL_HS                                                                                      Ungraded Detail: High school age students
SCH_STATUS_SPED                                                                               School Characteristics: Special education school
SCH_STATUS_MAGNET                                 School Characteristics: Magnet school or school operating a magnet program within the school
SCH_STATUS_CHARTER                                                                                      School Characteristics: Charter school
SCH_STATUS_ALT                                                                                      School Characteristics: Alternative school
SCH_ENR_HI_M                                                                                         Overall Student Enrollment: Hispanic Male
SCH_ENR_HI_F                                                                                       Overall Student Enrollment: Hispanic Female
SCH_ENR_AM_M                                                                    Overall Student Enrollment: American Indian/Alaska Native Male
SCH_ENR_AM_F                                                                  Overall Student Enrollment: American Indian/Alaska Native Female
SCH_ENR_AS_M                                                                                            Overall Student Enrollment: Asian Male
SCH_ENR_AS_F                                                                                          Overall Student Enrollment: Asian Female
SCH_ENR_HP_M                                                                 Overall Student Enrollment: Native Hawaiian/Pacific Islander Male
SCH_ENR_HP_F                                                               Overall Student Enrollment: Native Hawaiian/Pacific Islander Female
SCH_ENR_BL_M                                                                                            Overall Student Enrollment: Black Male
SCH_ENR_BL_F                                                                                          Overall Student Enrollment: Black Female
SCH_ENR_WH_M                                                                                            Overall Student Enrollment: White Male
SCH_ENR_WH_F                                                                                          Overall Student Enrollment: White Female
SCH_ENR_TR_M                                                                                Overall Student Enrollment: Two or More Races Male
SCH_ENR_TR_F                                                                              Overall Student Enrollment: Two or More Races Female
TOT_ENR_M                                                                                    Overall Student Enrollment: Calculated Male Total
TOT_ENR_F                                                                                  Overall Student Enrollment: Calculated Female Total
SCH_ENR_LEP_M                                                                                             Overall Student Enrollment: LEP Male
SCH_ENR_LEP_F                                                                                           Overall Student Enrollment: LEP Female
SCH_ENR_IDEA_M                                                                                           Overall Student Enrollment: IDEA Male
SCH_ENR_IDEA_F                                                                                         Overall Student Enrollment: IDEA Female
SCH_DUAL_IND                                                                                                 Dual Enrollment Program Indicator
SCH_DUALENR_HI_M                                                                                                Dual Enrollment: Hispanic Male
SCH_DUALENR_HI_F                                                                                              Dual Enrollment: Hispanic Female
SCH_DUALENR_AM_M                                                                           Dual Enrollment: American Indian/Alaska Native Male
SCH_DUALENR_AM_F                                                                         Dual Enrollment: American Indian/Alaska Native Female
SCH_DUALENR_AS_M                                                                                                   Dual Enrollment: Asian Male
SCH_DUALENR_AS_F                                                                                                 Dual Enrollment: Asian Female
SCH_DUALENR_HP_M                                                                        Dual Enrollment: Native Hawaiian/Pacific Islander Male
SCH_DUALENR_HP_F                                                                      Dual Enrollment: Native Hawaiian/Pacific Islander Female
SCH_DUALENR_BL_M                                                                                                   Dual Enrollment: Black Male
SCH_DUALENR_BL_F                                                                                                 Dual Enrollment: Black Female
SCH_DUALENR_WH_M                                                                                                   Dual Enrollment: White Male
SCH_DUALENR_WH_F                                                                                                 Dual Enrollment: White Female
SCH_DUALENR_TR_M                                                                                       Dual Enrollment: Two or More Races Male
SCH_DUALENR_TR_F                                                                                     Dual Enrollment: Two or More Races Female
TOT_DUAL_M                                                                                              Dual Enrollment: Calculated Male Total
TOT_DUAL_F                                                                                            Dual Enrollment: Calculated Female Total
SCH_DUALENR_LEP_M                                                                                                    Dual Enrollment: LEP Male
SCH_DUALENR_LEP_F                                                                                                  Dual Enrollment: LEP Female
SCH_DUALENR_IDEA_M                                                                                                  Dual Enrollment: IDEA Male
SCH_DUALENR_IDEA_F                                                                                                Dual Enrollment: IDEA Female
SCH_APENR_IND       Advanced Placement (AP) Program Indicator: Does this school have any students enrolled in Advanced Placement (AP) courses?
SCH_APENR_HI_M                                                                      Students Enrolled in at least one AP Course: Hispanic Male
SCH_APENR_HI_F                                                                    Students Enrolled in at least one AP Course: Hispanic Female
SCH_APENR_AM_M                                                 Students Enrolled in at least one AP Course: American Indian/Alaska Native Male
SCH_APENR_AM_F                                               Students Enrolled in at least one AP Course: American Indian/Alaska Native Female
SCH_APENR_AS_M                                                                         Students Enrolled in at least one AP Course: Asian Male
SCH_APENR_AS_F                                                                       Students Enrolled in at least one AP Course: Asian Female
SCH_APENR_HP_M                                              Students Enrolled in at least one AP Course: Native Hawaiian/Pacific Islander Male
SCH_APENR_HP_F                                            Students Enrolled in at least one AP Course: Native Hawaiian/Pacific Islander Female
SCH_APENR_BL_M                                                                         Students Enrolled in at least one AP Course: Black Male
SCH_APENR_BL_F                                                                       Students Enrolled in at least one AP Course: Black Female
SCH_APENR_WH_M                                                                         Students Enrolled in at least one AP Course: White Male
SCH_APENR_WH_F                                                                       Students Enrolled in at least one AP Course: White Female
SCH_APENR_TR_M                                                             Students Enrolled in at least one AP Course: Two or More Races Male
SCH_APENR_TR_F                                                           Students Enrolled in at least one AP Course: Two or More Races Female
TOT_APENR_M                                                                 Students Enrolled in at least one AP Course: Calculated Male Total
TOT_APENR_F                                                               Students Enrolled in at least one AP Course: Calculated Female Total
SCH_APENR_LEP_M                                                                          Students Enrolled in at least one AP Course: LEP Male
SCH_APENR_LEP_F                                                                        Students Enrolled in at least one AP Course: LEP Female
SCH_APENR_IDEA_M                                                                        Students Enrolled in at least one AP Course: IDEA Male
SCH_APENR_IDEA_F                                                                      Students Enrolled in at least one AP Course: IDEA Female
SCH_IBENR_IND                                                                          International Baccalaureate Diploma Programme Indicator
SCH_IBENR_HI_M                                                                                            IB Student Enrollment: Hispanic Male
SCH_IBENR_HI_F                                                                                          IB Student Enrollment: Hispanic Female
SCH_IBENR_AM_M                                                                       IB Student Enrollment: American Indian/Alaska Native Male
SCH_IBENR_AM_F                                                                     IB Student Enrollment: American Indian/Alaska Native Female
SCH_IBENR_AS_M                                                                                               IB Student Enrollment: Asian Male
SCH_IBENR_AS_F                                                                                             IB Student Enrollment: Asian Female
SCH_IBENR_HP_M                                                                    IB Student Enrollment: Native Hawaiian/Pacific Islander Male
SCH_IBENR_HP_F                                                                  IB Student Enrollment: Native Hawaiian/Pacific Islander Female
SCH_IBENR_BL_M                                                                                               IB Student Enrollment: Black Male
SCH_IBENR_BL_F                                                                                             IB Student Enrollment: Black Female
SCH_IBENR_WH_M                                                                                               IB Student Enrollment: White Male
SCH_IBENR_WH_F                                                                                             IB Student Enrollment: White Female
SCH_IBENR_TR_M                                                                                   IB Student Enrollment: Two or More Races Male
SCH_IBENR_TR_F                                                                                 IB Student Enrollment: Two or More Races Female
TOT_IBENR_M                                                                                       IB Student Enrollment: Calculated Male Total
TOT_IBENR_F                                                                                     IB Student Enrollment: Calculated Female Total
SCH_IBENR_LEP_M                                                                                                IB Student Enrollment: LEP Male
SCH_IBENR_LEP_F                                                                                              IB Student Enrollment: LEP Female
SCH_IBENR_IDEA_M                                                                                              IB Student Enrollment: IDEA Male
SCH_IBENR_IDEA_F                                                                                            IB Student Enrollment: IDEA Female

In [4]:
len(crdc_cols.index)

111

# Column info for nces_1516
<div class="alert alert-block alert-info">**17 Fields**

In [5]:
nces_cols = pd.read_csv('../filtered_data/01_nces_1516_initial_ccd_layout.csv')

In [6]:
"""Replace \n literals with commas for readability"""
nces_cols['Categorical Values'] = nces_cols['Categorical Values'].apply(lambda x: x.replace('\n', ', ') if type(x) == str else x)

In [7]:
with pd.option_context('display.max_colwidth', 350, 'display.max_rows', 25):
    display(nces_cols[['Variable Name', 'Description', 'Categorical Values']])

,Variable Name,Description,Categorical Values
0,LEAID,NCES Agency Identification Number,NaN
1,LEA_NAME,LEA Name,NaN
2,SCHID,NCES school identifier,NaN
3,STABR,State Abreviation,NaN
4,SCH_NAME,School name,NaN
5,TITLEI,Title I Eligible School. This flag indicates whether a school is eligible for participation in either TAS or SWP program authorized by Title I of Public Law 103-382.,"No, Yes, Missing, Not applicable, -9-Suppressed"
6,SCH_TYPE_TEXT,School type (description),"Alternative Education School, Regular School, Special Education School, Vocational Education School,"
7,SCH_TYPE,School type (code),"1 = Regular school, 2 = Special education school, 3 = Vocational school, 4 = Other/alternative school, 5 = Reportable program (new code starting in 2007–08),"
8,LEVEL,School level,"1 = Primary (low grade = PK through 03; high grade = PK through 08), 2 = Middle (low grade = 04 through 07; high grade = 04 through 09), 3 = High (low grade = 07 through 12; high grade = 12 only), 4 = Other (any other configuration not falling within the above three categories;including ungraded), N = Not applicable, ,"
9,VIRTUAL,Virtual School Status,"Missing, No, Yes"
10,GSLO,Lowest Grade Offered,NaN
11,GSHI,Highest Grade Offered,NaN
12,combokey,nces + schid unique identifier,NaN
13,NMCNTY15,County Code,NaN
14,LOCALE15,Locale Code,NaN
15,LAT1516,Latitude,NaN
16,LON1516,Longitutde,NaN

In [8]:
len(nces_cols.index)

17

# <font color = green> II. Data Cleaning/Joining </font>

# crdc_1516 Data
<div class="alert alert-block alert-info"><b> 96,360 Schools before any filtering <br>
111 Fields (Matches the crdc_cols)</b></div>
<br><br>
Used combokey_convert.converter to create a csv-compatible "COMBOKEY"

In [9]:
crdc_1516 = pd.read_csv('../filtered_data/00_crdc_1516_initial.csv', 
                        dtype = {'LEAID':np.object})

In [10]:
crdc_1516['COMBOKEY'] = combokey_converter.convert(crdc_1516, 'LEAID', 'SCHID')

In [11]:
crdc_1516.head()

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,COMBOKEY,JJ,SCH_GRADE_PS,SCH_GRADE_KG,...,SCH_IBENR_WH_M,SCH_IBENR_WH_F,SCH_IBENR_TR_M,SCH_IBENR_TR_F,TOT_IBENR_M,TOT_IBENR_F,SCH_IBENR_LEP_M,SCH_IBENR_LEP_F,SCH_IBENR_IDEA_M,SCH_IBENR_IDEA_F
0,AL,ALABAMA,100002,Alabama Youth Services,1705,Wallace Sch - Mt Meigs Campus,='010000201705',Yes,No,No,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
1,AL,ALABAMA,100002,Alabama Youth Services,1706,McNeel Sch - Vacca Campus,='010000201706',Yes,No,No,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
2,AL,ALABAMA,100002,Alabama Youth Services,1876,Alabama Youth Services,='010000201876',No,No,No,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
3,AL,ALABAMA,100002,Alabama Youth Services,99995,AUTAUGA CAMPUS,='010000299995',Yes,No,No,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9
4,AL,ALABAMA,100005,Albertville City,870,Albertville Middle School,='010000500870',No,No,No,...,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9

In [12]:
len(crdc_1516.index)

96360

In [13]:
len(crdc_1516.columns)

111

# nces_1516 Data
<div class="alert alert-block alert-info"><b> The nces_1516 Data was recorded in separate files (each with different numbers of schools), so I will have to join the separate files to avoid corruption/loss of data. </b><br>
    <u>Files</u><br>
    1. Characteristics <br>
    2. Directory <br>
    3. Geographic <br>
</div><div class = 'alert alert-block alert-info'>
Like the crdc data, the combokey field was generated using my combokey_converter.convert function.<br></div>

<div class="alert alert-block alert-warning">
1. **100232 Initial Schools**<br><br>
2. **After first inner join (Directory and Characteristics) --> 100232 schools**<br>
Note: I ran a check to ensure that all of the matching combokeys have matching school names -- 100% identical.<br><br>
3. **After second inner join (above_combined and Geographic) --> 100087**<br> Note:  I ran the same check to ensure that all of the schools matched and nearly 9000 came back as non-matching.  I then compared the first word of each of the two name fields, and only 9 schools came back as non-matching.  After close examination, I decided to cull these 9 schools.<br></div><div class = 'alert alert-block alert-warning'>
**CSV saved to '../filtered_data/01_nces_1516_initial_ccd.csv'**

In [14]:
nces_1516_characteristics = pd.read_csv('../filtered_data/01_nces_1516_initial_school_characteristics.csv')

In [15]:
nces_1516_characteristics['combokey'] = combokey_converter.convert(nces_1516_characteristics, 'LEAID', 'SCHID')

In [16]:
len(nces_1516_characteristics.index)

100232

In [17]:
nces_1516_directory = pd.read_csv('../filtered_data/01_nces_1516_initial_school_directory.csv')

In [18]:
nces_1516_directory['combokey'] = combokey_converter.convert(nces_1516_directory, 'LEAID', 'SCHID')

**First Join:  Directory + Characteristics**

In [19]:
nces_1516 = nces_1516_characteristics.set_index('combokey').join(nces_1516_directory.set_index('combokey'), how = 'inner', lsuffix = 'dir_')

In [20]:
len(nces_1516.index)

100232

In [21]:
len(nces_1516[nces_1516.SCH_NAME == nces_1516.SCH_NAMEdir_].index)

100232

In [22]:
nces_1516 = nces_1516.drop(['LEAIDdir_', 'SCHIDdir_', 'SCH_NAMEdir_'], axis = 1)

**Second Join: combined + geo**

In [23]:
nces_1516_geo = pd.read_csv('../filtered_data/01_nces_1516_initial_geographic.csv',  dtype = {'LOCALE15': np.object})

In [24]:
nces_1516_geo['combokey'] = combokey_converter.convert(nces_1516_geo, 'LEAID', 'SCHID')

In [25]:
nces_1516_test = nces_1516.join(nces_1516_geo.set_index('combokey'), how = 'inner', rsuffix = 'dir_')

In [26]:
len(nces_1516_test.index)

100096

In [27]:
"""How many schools have matching School Names between CRDC and NCES?"""
len(nces_1516_test[nces_1516_test.SCH_NAME == nces_1516_test.NAME].index)

91091

In [28]:
def name_checker(sch1, sch2):
    sch1 = sch1.lower()
    sch2 = sch2.lower()
    
    if sch1[0] == sch2[0]:
        return 0
    return 1

nces_1516_test['no_match_name'] = nces_1516_test.apply(lambda row: name_checker(row['SCH_NAME'], row['NAME']), axis = 1)
nces_1516_test[nces_1516_test.no_match_name == 1][['NAME', 'SCH_NAME']]

,NAME,SCH_NAME
combokey,,
='051266001562',HYLTON JUNIOR HIGH SCHOOL,LAKESIDE JUNIOR HIGH SCHOOL
='090147001810',Stowe - Early Learning Center (S,EPS PK STEAM Academy
='090171001700',Alternative High School Programs,Greenwich Alternative High School
='090192001616',STEM Magnet School at Dwight,Betances STEM Magnet School
='090279000148',Hyde School of Health Science an,Cortlandt V.R. Creed Health and Sport Sciences...
='090279001543',Helene Grant Headstart,Dr. Mayo Early Childhood School
='090279001585',Katherine Brennan/Clarence Roger,Brennan Rogers School
='090351201476',Education Connection Special Edu,GFLC/ACCESS School
='090423001808',Hatton Preschool Program,Southington Public Schools Preschool Program a...

In [29]:
nces_1516_full = nces_1516_test[nces_1516_test.no_match_name == 0].drop(['LEAIDdir_', 'SCHIDdir_', 'no_match_name', 'NAME'], axis = 1)

In [30]:
nces_1516_full.head()

,TITLEI,LEAID,LEA_NAME,STABR,SCHID,SCH_NAME,SCH_TYPE_TEXT,SCH_TYPE,LEVEL,VIRTUAL,GSLO,GSHI,NMCNTY15,LOCALE15,LAT1516,LON1516
combokey,,,,,,,,,,,,,,,,
='010000200277',-9,100002,Alabama Youth Services,AL,277,Sequoyah Sch - Chalkville Campus,Alternative Education School,4,3,No,7,12,Jefferson County,21,33.673661,-86.628755
='010000201667',-9,100002,Alabama Youth Services,AL,1667,Camps,Alternative Education School,4,3,No,7,12,Autauga County,41,32.521681,-86.530132
='010000201670',-9,100002,Alabama Youth Services,AL,1670,Det Ctr,Alternative Education School,4,3,No,7,12,Clarke County,41,31.938444,-87.750529
='010000201705',-9,100002,Alabama Youth Services,AL,1705,Wallace Sch - Mt Meigs Campus,Alternative Education School,4,3,No,7,12,Montgomery County,41,32.374812,-86.082360
='010000201706',-9,100002,Alabama Youth Services,AL,1706,McNeel Sch - Vacca Campus,Alternative Education School,4,3,No,7,12,Jefferson County,12,33.583385,-86.710058

In [31]:
len(nces_1516_full.index)

100087

In [32]:
# nces_1516_full.to_csv('../filtered_data/01_nces_1516_initial_combined_ccd.csv')

# NCES (combined) and CRDC join
<div class="alert alert-block alert-warning">Out of the 96360 schools in the crdc1516 dataset, <b>3861</b> schools did not have a matching Combokey. These non-matching schools were kept in the dataset.<br><br>

Using the name checker function from above, another <b>182</b> schools were found to have School Names whose first words did not match between the NCES and CRDC sets.  Airing on the side of caution, these schools were indiscriminately culled.<br><br>

**Final school count in the combined dataset:  96178**</div>
<div class = 'alert alert_block alert-info'>Dataset saved to '03_crdc_nces_1516_raw_combined.csv'

In [33]:
crdc_nces1516_test = crdc_1516.set_index('COMBOKEY').join(nces_1516_full, how = 'left', rsuffix=('_'))

In [34]:
crdc_nces1516_test[crdc_nces1516_test.SCH_NAME_.isnull()].LEAID.count()

3861

In [35]:
def name_checker(sch1, sch2):
    if type(sch2) == float:
        return 2
    else:
        sch1 = sch1.lower()
        sch2 = sch2.lower()
        
    if sch1[0] == sch2[0]:
        return 0
    return 1

crdc_nces1516_test['no_match_name'] = crdc_nces1516_test.apply(lambda row: name_checker(row['SCH_NAME'], row['SCH_NAME_']), axis = 1)

In [36]:
"""How many schools don't have matching Schools Names (from the CRDC and NCES datasets, respectively)"""
len(crdc_nces1516_test[crdc_nces1516_test.no_match_name == 1][['SCH_NAME', 'SCH_NAME_']].index)

182

In [37]:
crdc_nces_1516 = crdc_nces1516_test[crdc_nces1516_test.no_match_name != 1].drop(['LEA_NAME_', 'LEAID_', 'SCHID_', 'SCH_NAME_', 'no_match_name'], axis = 1)

In [38]:
len(crdc_nces_1516.index)

96178

In [39]:
crdc_nces_1516 = crdc_nces_1516.fillna('Missing')

In [40]:
# crdc_nces_1516.to_csv('../filtered_data/03_crdc_nces_1516_raw_combined.csv')

# <font color = green> IV. Filtration </font>

# Select Non-[Junvile Justice, Special Education, and Alternative Schools]
<div class = 'alert alert-block alert-info'>Schools that answered 'No' to each of those three questions on the CRDC Sruvey.<br><br> 
I also used a keyword filter to remove any remaining "Juvenile Justice"-eque Institutions.</div>
<div class = 'alert alert-block alert-warning'>**90448** Schools Remain</div>

In [41]:
filter1_crdc_nces_1516 = crdc_nces_1516[(crdc_nces_1516.JJ == 'No') & (crdc_nces_1516.SCH_STATUS_ALT == 'No') & (crdc_nces_1516.SCH_STATUS_SPED == 'No')]

In [42]:
def jj_keyword_remove(name):
    kws = ['behavioral', 'juvenile', 'correction']
    for kw in kws:
        if kw in name.strip().lower():
            return False
    return True

filter1_crdc_nces_1516 = filter1_crdc_nces_1516[filter1_crdc_nces_1516.SCH_NAME.apply(lambda x: jj_keyword_remove(x))]
filter1_crdc_nces_1516 = filter1_crdc_nces_1516[filter1_crdc_nces_1516.LEA_NAME.apply(lambda x: jj_keyword_remove(x))]

In [43]:
len(filter1_crdc_nces_1516.index)

90448

# Select Schools with Lowest Grade (9-12) or Highest Grade (12) or Ungraded HS-students
<div class = 'alert alert-block alert-info'>I made formulas that take in the data from CRDC (because there are no null values for the Grade Enrollment Flags), and determines: (1) if a school's lowest grade offered is above 9, (2) if it contains ungraded HS-aged studnets, and (3) if a school's highest grade offered is 12th.<br><br>While NCES CCD does have columns for lowest and highest grades, there were many null values, so the filtration may have been too intense.</div>
<div class = 'alert alert-block alert-warning'>**21606** Schools Remain</div>

In [44]:
"""How many missing values in the grade columns?"""
np.sum(filter1_crdc_nces_1516.SCH_GRADE_G01.isnull())

0

In [45]:
def lowest_grade_9orAbove(g9, g10, g11, g12, ug, ug_hs):
    """Inputs all of the grade enrollment flags from the CRDC dataset
        Returns a label representing whether or not a school's lowest grade is 9, 10, 11, or 12 
        (or if a school is ungraded, but has hs-aged students)
        """
    if ug == 'Yes':
        if ug_hs == 'Yes': 
            return 'UG-Yes'
        else:
            return 'UG-No'

    if g9 == 'Yes':
        return 'Yes'
    if g10 == 'Yes':
        return 'Yes'
    if g11 == 'Yes':
        return 'Yes'
    if g12 == 'Yes':
        return 'Yes'
    return 'No'

In [46]:
def highest_grade_12(g12):
    """Inputs all of the grade enrollment flags from the CRDC dataset
        Returns a label representing whether or not a school's highest grade is 12.
        """
    
    if g12 == 'Yes':
        return 'Yes'
    return 'No'

In [47]:
filter2_crdc_nces_1516 = filter1_crdc_nces_1516.copy()
filter2_crdc_nces_1516['Low_Grade_Above9'] = filter2_crdc_nces_1516.apply(lambda row: lowest_grade_9orAbove(row['SCH_GRADE_G09'], row['SCH_GRADE_G10'], row['SCH_GRADE_G11'], row['SCH_GRADE_G12'], row['SCH_GRADE_UG'], row['SCH_UGDETAIL_HS']), axis = 1)

In [48]:
filter2_crdc_nces_1516['High_Grade_12'] = filter2_crdc_nces_1516.apply(lambda row: highest_grade_12(row['SCH_GRADE_G12']), axis = 1)

In [49]:
"""Breakdown of Schools with a Lowest Grade Above 9 (or with Ungrade HS-aged Students)"""
filter2_crdc_nces_1516.Low_Grade_Above9.value_counts()

No        66886
Yes       19771
UG-No      2294
UG-Yes     1497
Name: Low_Grade_Above9, dtype: int64

In [50]:
"""Breakdown of Schools with a Highest Grade of 12"""
filter2_crdc_nces_1516.High_Grade_12.value_counts()

No     70094
Yes    20354
Name: High_Grade_12, dtype: int64

In [51]:
filter2_crdc_nces_1516 = filter2_crdc_nces_1516[(filter2_crdc_nces_1516.Low_Grade_Above9 == 'Yes') | (filter2_crdc_nces_1516.Low_Grade_Above9 == 'UG-Yes') | (filter2_crdc_nces_1516.High_Grade_12 == 'Yes')]

In [52]:
len(filter2_crdc_nces_1516.index)

21606

# Remove Virtual Schools
<div class = 'alert alert-block alert-info'>
1. Remove any Schools that reported 'Yes' to the Virtual Schools Question<br>
2. Remove Schools that have certain keyword that likely indicate an online school
</div>
<div class = 'alert alert-block alert-warning'>**21209** Schools Remain</div>

In [53]:
filter2_crdc_nces_1516.VIRTUAL.value_counts()

No         17408
Missing     3867
Yes          331
Name: VIRTUAL, dtype: int64

In [54]:
filter3_crdc_nces_1516 = filter2_crdc_nces_1516[filter2_crdc_nces_1516.VIRTUAL != 'Yes']

In [55]:
len(filter3_crdc_nces_1516.index)

21275

In [56]:
def any_missed_virtuals(name):
    kws = ['virtual', 'cyber', 'electronic', 'internet', 'online', 'distance']
    for kw in kws:
        if kw in name.strip().lower():
            return False
    return True

filter3_crdc_nces_1516 = filter3_crdc_nces_1516[filter3_crdc_nces_1516.SCH_NAME.apply(lambda x: any_missed_virtuals(x))]

In [57]:
len(filter3_crdc_nces_1516.index)

21209

# Remove schools reported as elementary, middle, or "Other"
<div class = 'alert alert-block alert-info'>Even with the Lowest/Highest Grade filter, I wanted to ensure that no non-typical high schools (as reported by the NCES's LEVEL Field) are retained.  The Other category is perhaps the most important to cull here, as many of the very, very large charter-type schools are listed in this category.
<br><br>
Schools with Missing Values were retained.
</div>
<div class = 'alert alert-block alert-warning'>**17542** Schools Remain</div>

In [58]:
filter4_crdc_nces_1516 = filter3_crdc_nces_1516.copy()

In [59]:
filter4_crdc_nces_1516.LEVEL.value_counts()

3          16348
4           3214
Missing     1194
2            307
1             76
N             70
Name: LEVEL, dtype: int64

In [60]:
filter4_crdc_nces_1516 = filter4_crdc_nces_1516[(filter4_crdc_nces_1516.LEVEL == 'Missing') | (filter4_crdc_nces_1516.LEVEL == '3')]

In [61]:
len(filter4_crdc_nces_1516.index)

17542

# Select Schools reported as Regular
<div class = 'alert alert-block alert-info'>Removed Schools with a SCH_TYPE that was not 1 (Regular).  Culls additional "Special Education", "Vocational", and "Alternative/Other" schools.
<br><br>
Schools with Missing Values were retained.
</div>
<div class = 'alert alert-block alert-warning'>**16451** Schools Remain</div>

In [62]:
filter5_crdc_nces_1516 = filter4_crdc_nces_1516.copy()

In [63]:
filter5_crdc_nces_1516.SCH_TYPE.value_counts()

1.0        15257
Missing     1194
4.0          744
3.0          332
2.0           15
Name: SCH_TYPE, dtype: int64

In [64]:
filter5_crdc_nces_1516 = filter5_crdc_nces_1516[(filter5_crdc_nces_1516.SCH_TYPE == 'Missing') | (filter5_crdc_nces_1516.SCH_TYPE == 1)]

In [65]:
len(filter5_crdc_nces_1516.index)

16451

# <font color = green> V. Dealing with Missing Values </font>
<div class = 'alert alert-cell alert-info'> With nearly 1200 schools missing NCES data, include schools from prominent districts like "NEW YORK CITY PUBLIC SCHOOLS" and "Green Dot Public Schools," it is important to try to recover as much of these schools as possible.
<br><br>
The problem that I found was that the CRDC lumped a number of school districts together; therefore, the combokeys of schools in these districts do not match those of the NCES.
</div>

<div class = 'alert alert-cell alert-info'>
**I tried a number of methods to try to properly join these missing schools:**<br>
- Using only the school name:  This had difficulties because there are many schools that share the same name, so when a join is implemented, these schools are given all of the values of the other schools (i.e. it creates a lot of duplicate values).
- Using the NCES data from 2013:  This was also problematic, as most of the same schools that were missing in this dataset were also constrained to the same problem in the 2013-2014 dataset.<br>
- Using the District and the name together:  This also suffered from the fact that the CRDC data combines some school districts; therefore, the names of the districts still did not match up.<br>
- **Finally, I used a combination of the name of the school and the state:  There were only a handfull in the dataset containing the missing values.**<br><br>
</div>

<div class = 'alert alert-cell alert-warning'>
**821 (out of 1194)** Missing Schools were recovered using this method </div>

<div class = 'alert alert-cell alert-info'>
Next, I recovered the remaining schools in the 'New York City Public Schools District', because it was clear that they were simply missing due to a LEA reporting error in the CRDC data.  This process was two-parted:<br>
- First, Because it seemed as though most of these remaining New York schools had the incorrect LEAID, I used the the school id and state abreviation to create a unique identifier.<br>
- Second, I used the NCES database to manually search for the remaining schools correct their combokey
</div>

<div class = 'alert alert-cell alert-warning'>
**36** More High Schools Recovered  </div>

<div class = 'alert alert-cell alert-info'>
I performed the same (nces-provided field)-filtration steps on the recovered data.  Then, I hand-removed duplicate values by checking the original filtered data for matching records. </div>

<div class = 'alert alert-cell alert-warning'>
**468** Recovered High Schools Total  </div>

In [66]:
"""Which districts had the most missing schools?"""
with pd.option_context('display.max_rows', 1200):
    display(filter5_crdc_nces_1516[filter5_crdc_nces_1516.LEVEL == 'Missing'].groupby('LEA_NAME')['LEAID'].count().sort_values(ascending = False))

LEA_NAME
NEW YORK CITY PUBLIC SCHOOLS                                                               615
Green Dot Public Schools                                                                    11
NORMAN                                                                                       9
Peters Township SD                                                                           6
Dept. of Svs. for Children Youth & Their Families                                            5
Boston                                                                                       4
Ombudsman Educational Services Ltd. a subsidiary of Educ 2                                   4
OFFICE OF EDUCATION DEPARTMENT OF CHILDREN AND FAMILIES                                      4
Cherokee County                                                                              3
NASSAU BOCES                                                                                 3
WINDSOR SCHOOL DISTRICT                                                                      3
ERIE 2-CHAUTAUQUA-CATTARAUGUS BOCES                                                          3
TULSA                                                                                        3
Coweta County                                                                                3
Learning Tree Inc                                                                            3
Geauga County Educational Service Center                                                     3
Ombudsman Educational Services Ltd. a subsidiary of Educ 1                                   3
Clayton County                                                                               3
Cobb County                                                                                  2
Cleveland Metropolitan School District                                                       2
Mesa Unified District                                                                        2
BLaST IU 17                                                                                  2
BOLIVAR R-I                                                                                  2
Harris County                                                                                2
ORLEANS-NIAGARA BOCES                                                                        2
Forsyth County Schools                                                                       2
TRINITY CHARTER SCHOOL                                                                       2
Cincinnati City                                                                              2
Horry 01                                                                                     2
HARRIS COUNTY DEPT OF ED                                                                     2
Brownsburg Community Sch Corp                                                                2
Burlington School District                                                                   2
SPRINGDALE SCHOOL DISTRICT                                                                   2
St. Mary's County Public Schools                                                             2
ONONDAGA-CORTLAND-MADISON BOCES                                                              2
NEW HAVEN SCHOOL DISTRICT                                                                    2
LAS CRUCES PUBLIC SCHOOLS                                                                    2
LEWISVILLE ISD                                                                               2
Horizon Charter                                                                              2
New Brunswick School District                                                                2
PRIORITY CHARTER SCHOOLS                                                                     2
Linn Benton Lincoln ESD                                                                      2
Academy School District 20                                                                   2
PACIFIC CHARTER INSTITUTE                                                                    2
FAIRFAX CO PBLC SCHS                                                                         1
ESCUELA POPULAR ACCELERATED FAMILY LRN                                                       1
ESCONDIDO CHARTER HIGH                                                                       1
EQUALITY CHARTER SCHOOL                                                                      1
EPIC de Cesar Chavez                                                                         1
ENVISION ACADEMY FOR ARTS & TECHNOLOGY                                                       1
GREEN COUNTRY TECHNOLOGY CTR                                                                 1
GROTON SCHOOL DISTRICT                                                                       1
Gateway College And Career Academy                                                           1
ENVIRONMENTAL SCIENCE AND TECHNOLOGY HIGH SCHOOL                                             1
Gateway Public Schools                                                                       1
ENID                                                                                         1
EL CAMINO REAL CHARTER HIGH SCHOOL                                                           1
EAST WINDSOR SCHOOL DISTRICT                                                                 1
Gertz-Ressler/Richard Merkin 6-12 Complex                                                    1
Gilmer County                                                                                1
Glenwood Mental Health Services                                                              1
GRAPEVINE-COLLEYVILLE ISD                                                                    1
EXCELLENCE GIRLS CHARTER SCHOOL                                                              1
ESCUELA POPULAR/CENTER FOR TRAINING AND CAREERS, F                                           1
FARMINGTON MUNICIPAL SCHOOLS                                                                 1
Executive Preparatory Academy of Finance                                                     1
FUTURES HIGH                                                                                 1
Glynn County                                                                                 1
Everest Public High School                                                                   1
Evart Public Schools                                                                         1
Encore High School for the Arts                                                              1
Empire Springs Charter                                                                       1
Eldora State Training School for Boys                                                        1
El Camino Real Academy                                                                       1
Friendship PCS                                                                               1
GENESEE VALLEY BOCES                                                                         1
GERING PUBLIC SCHOOLS                                                                        1
Ednovate - USC East College Prep                                                             1
GOLDEN EAGLE CHARTER                                                                         1
East Orange School District                                                                  1
GRANADA HILLS CHARTER HIGH                                                                   1
Early County                                                                                 1
LA FERIA ISD                                                                                 1
Greenfield-Central Com Schools                                                               1
Gold Rush Charter                                                                            1
JULIAN CHARTER                                                                               1
IVY ACADEMIA                                                                                 1
Indpls Lighthouse Charter School                                                             1
Insight @ San Joaquin                                                                        1
Inspire Charter School                                                                       1
Inspire Charter School - South                                                               1
Institute for Transformative Education  Inc.                                                 1
International Academy of Macomb                                                              1
Iola                                                                                         1
IvyTech Charter                                                                              1
JUAN BAUTISTA DE ANZA                                                                        1
JUBILEE ACADEMIC CENTER                                                                      1
Jackson ISD                                                                                  1
IMPACT ACADEMY OF ARTS & TECHNOLOGY                                                          1
Jackson Preparatory & Early College                                                          1
Jefferson Union High                                                                         1
John Adams Academy                                                                           1
John Henry High                                                                              1
KIPP KING COLLEGIATE HIGH                                                                    1
KIPP SAN JOSE COLLEGIATE                                                                     1
KIPP San Francisco College Prep                                                              1
KIRKSVILLE R-III                                                                             1
KREMLIN-HILLSDALE                                                                            1
Kestrel Schools  Inc.                                                                        1
Konocti Unified                                                                              1
INSTITUTIONAL EDUCATIONAL PROGRAMS                                                           1
Huron Valley Schools                                                                         1
Gompers Preparatory Academy                                                                  1
HEALTH SERVICES ACADEMY HIGH SCHOOL                                                          1
Greater Randolph Interlocal Coop                                                             1
Green County                                                                                 1
LARCHMONT CHARTER                                                                            1
Greene County ESC                                                                            1
L'Anse Creuse Public Schools                                                                 1
Guajome Park Academy Charter                                                                 1
Gull Lake Community Schools                                                                  1
EAST MTN HIGH SCHOOL                                                                         1
HARLEM VILLAGE ACADEMY CHARTER SCHOOL EHVACS                                                 1
HARLEM VILLAGE ACADEMY LEADERSHIP CHARTER SCHOOL                                             1
HART ISD                                                                                     1
HENRY CO PBLC SCHS                                                                           1
Humphreys College Academy Of Business Law And Education                                      1
HERKIMER-FULTON-HAMILTON-OTSEGO BOCES                                                        1
HERON LAKE-OKABENA SCHOOL DISTRICT                                                           1
HIGH TECH LA                                                                                 1
HUME LAKE CHARTER                                                                            1
Harbor Springs Charter School                                                                1
Henry County                                                                                 1
Higdon Hill School                                                                           1
Hillsdale Community Schools                                                                  1
Holland City School District                                                                 1
HomeTech Charter                                                                             1
Hood River County SD                                                                         1
HAMILTON-FULTON-MONTGOMERY BOCES                                                             1
iLEAD Hybrid                                                                                 1
Dysart Unified School District                                                               1
Dodge County                                                                                 1
Anahuacalmecac International University Preparatory                                          1
Aspire Alexander Twilight Secondary Academy                                                  1
Aspire Langston Hughes Academy                                                               1
Aspire Ollin University Preparatory Academy                                                  1
Aspire Richmond Ca. College Preparatory Academy                                              1
Aspire Vanguard College Preparatory Academy                                                  1
Assurance Learning Academy                                                                   1
Atlanta Public Schools                                                                       1
Atlantis Charter (District)                                                                  1
B. Roberto Cruz Leadership Academy                                                           1
BAY AREA TECHNOLOGY                                                                          1
BELCOURT 7                                                                                   1
BIG PICTURE HS - FRESNO                                                                      1
BIRMINGHAM COMMUNITY CHARTER HIGH                                                            1
BOONE CENTRAL SCHOOLS                                                                        1
BRIGHT STAR SECONDARY CHARTER ACADEMY                                                        1
BROOKLYN ASCEND CHARTER SCHOOL                                                               1
BURNS FLAT-DILL CITY                                                                         1
Benton Area SD                                                                               1
Berea City                                                                                   1
Bergen Arts and Sciences Charter School                                                      1
Bibb County                                                                                  1
Bloomfield Hills Schools                                                                     1
Brewer-Porch Childrens Center                                                                1
Burlington Area School District                                                              1
Burton Technology Academy High School                                                        1
Butler Area SD                                                                               1
American Indian Public High School                                                           1
Alternatives in Action                                                                       1
Alta Vista South Public Charter                                                              1
Abraxis Charter                                                                              1
ACE Charter High                                                                             1
ACLD TILLOTSON SCHOOL                                                                        1
ALAMEDA COMMUNITY LEARNING CENTER                                                            1
ALTA VISTA PUBLIC                                                                            1
ANAHUAC ISD                                                                                  1
APEX Academy                                                                                 1
ARISE High School                                                                            1
ASPIRE BENJAMIN HOLT COLLEGE PREPARATORY ACADEMY                                             1
ASPIRE EAST PALO ALTO PHOENIX ACADEMY                                                        1
ASPIRE GOLDEN STATE COLLEGE PREPARATORY ACADEMY                                              1
ASPIRE LIONEL WILSON COLLEGE PREPARATORY ACADEMY                                             1
ASPIRE PACIFIC ACADEMY                                                                       1
Academy for Academic Excellence                                                              1
Alpha Cindy Avitia High                                                                      1
Academy of Arts and  Sciences Del Mar Middle & High 6-12                                     1
Academy of Arts and  Sciences El Cajon Middle and High 6-12                                  1
Academy of Arts and  Sciences Oxnard & Ventura                                               1
Academy of Arts and  Sciences Thousand Oaks and Simi                                         1
Academy of Arts and Sciences Sonoma                                                          1
Academy of Arts and Sciences: Los Angeles (9-12)                                             1
Accelerated Achievement Academy (Ukiah)                                                      1
Albert Einstein Academy for Letters Arts and Sciences                                        1
Alliance Alice M. Baxter College-Ready High                                                  1
Alliance Margaret M. Bloomfield Technology Academy High                                      1
Alliance Renee and Meyer Luskin High School                                                  1
Alliance Susan and Eric Smidt Technology High School                                         1
CAMDENTON R-III                                                                              1
CAMINO NUEVO CHARTER HIGH                                                                    1
CASS LAKE-BENA PUBLIC SCHOOLS                                                                1
DIVISION OF YOUTH SERVICES                                                                   1
Colonial School District                                                                     1
Community Collaborative Charter (Acton)                                                      1
Connecticut Technical High School System                                                     1
Conservatory of Vocal/Instrumental Arts High                                                 1
Constellation Schools: Parma Community                                                       1
Corrales International School Charter School                                                 1
Creekside Charter Management                                                                 1

In [67]:
filter5_missing_leas = filter5_crdc_nces_1516[filter5_crdc_nces_1516.LEVEL == 'Missing'].groupby('LEA_NAME')['LEAID'].count().sort_values(ascending = False)

In [68]:
# filter5_missing_leas.to_csv('../filtered_data/04_inital_filter_missing_LEAs.csv')

In [69]:
"""How many missing schools?"""
filter5_missing_schools = filter5_crdc_nces_1516[filter5_crdc_nces_1516.LEVEL == 'Missing']
len(filter5_missing_schools.index)

1194

In [70]:
# filter5_missing_schools.to_csv('../filtered_data/04_intital_filter_missing_schools.csv')

** Manipulate missing schools and original nces data --> join **

In [71]:
filter5_schname_state = filter5_missing_schools.copy()

In [72]:
filter5_schname_state = filter5_schname_state.reset_index()

In [73]:
filter5_schname_state['SCH_NAME'] = filter5_schname_state['SCH_NAME'].apply(lambda x: x.lower())
filter5_schname_state['SCH_NAME_ST_NUM'] = filter5_schname_state.SCH_NAME + filter5_schname_state.LEA_STATE

In [74]:
"""How many duplicate schools in the filter5 dataset?"""
filter5_schname_state.groupby('SCH_NAME_ST_NUM')['SCH_NAME_ST_NUM'].count().sort_values(ascending = False).head(10)

SCH_NAME_ST_NUM
performance learning centerGA                   2
community collaborative charterCA               2
harlem village academies highNY                 2
yuba city charterCA                             1
foreign language academy of global studiesNY    1
flint river programGA                           1
flushing high schoolNY                          1
flushing international high schoolNY            1
food and finance high schoolNY                  1
fordham high school for the artsNY              1
Name: SCH_NAME_ST_NUM, dtype: int64

In [75]:
filter5_schname_state[filter5_schname_state.SCH_NAME_ST_NUM == 'performance learning centerGA']

,COMBOKEY,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,JJ,SCH_GRADE_PS,SCH_GRADE_KG,...,VIRTUAL,GSLO,GSHI,NMCNTY15,LOCALE15,LAT1516,LON1516,Low_Grade_Above9,High_Grade_12,SCH_NAME_ST_NUM
334,='130129003727',GA,GEORGIA,1301290,Cobb County,3727,performance learning center,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Yes,Yes,performance learning centerGA
346,='130270003728',GA,GEORGIA,1302700,Harris County,3728,performance learning center,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Yes,Yes,performance learning centerGA

In [76]:
nces_1516_schname_state = nces_1516_full.copy()

In [77]:
nces_1516_schname_state = nces_1516_schname_state.reset_index()

In [78]:
nces_1516_schname_state['SCH_NAME'] = nces_1516_schname_state['SCH_NAME'].apply(lambda x: x.lower())
nces_1516_schname_state['SCH_NAME_ST_NUM'] = nces_1516_schname_state.SCH_NAME + nces_1516_schname_state.STABR

In [79]:
"""Join the NCES and filter5 datasets on the SCH_NAME_ST_NUM column"""
schname_combined = filter5_schname_state.set_index('SCH_NAME_ST_NUM').join(nces_1516_schname_state.set_index('SCH_NAME_ST_NUM'), how = 'left', rsuffix = '_')

In [80]:
"""How many schools have duplicated values?"""
schname_combined.SCH_NAME_.value_counts().sort_values(ascending = False).head(10)

tarrant co j j a e p                    6
community collaborative charter         4
accelerated achievement academy         2
hart el                                 2
beacon high school                      2
performance learning center             2
university high                         2
academy of arts and sciences: sonoma    1
stuyvesant high school                  1
ps 284 lew wallace                      1
Name: SCH_NAME_, dtype: int64

In [81]:
"""How may more schools were matched?"""
len(schname_combined[schname_combined.SCH_NAME_.notnull()].index)

821

In [82]:
"""How mnay schools still did not have a match?"""
len(schname_combined[schname_combined.SCH_NAME_.isnull()].index)

384

## Recover the NY Schools

In [83]:
schname_combined_missing = schname_combined.copy()
schname_combined_missing = schname_combined_missing[schname_combined_missing.SCH_NAME_.isnull()]

schname_combined_missing_ny = schname_combined_missing.copy()
schname_combined_missing_ny = schname_combined_missing_ny[schname_combined_missing_ny['LEA_NAME'] == 'NEW YORK CITY PUBLIC SCHOOLS']

In [84]:
print(len(schname_combined_missing_ny.index))
print(schname_combined_missing_ny.SCHID.nunique())

36
36

In [85]:
schname_combined_missing_ny = schname_combined_missing_ny.drop(['TITLEI_', 'STABR_', 'SCH_TYPE_TEXT_', 'SCH_TYPE_',
                                                                'LEVEL_', 'VIRTUAL_', 'GSLO_', 'GSHI_', 
                                            'NMCNTY15_', 'LOCALE15_', 'LAT1516_', 'LON1516_', 'combokey',
                                            'LEAID_', 'LEA_NAME_', 'SCH_NAME_', 'SCHID_'], axis = 1)

In [86]:
def schid_state_maker(schid, state):
    schid = str(schid).zfill(5)
    return schid + state

In [87]:
schname_combined_missing_ny['schid_state'] = schname_combined_missing_ny.apply(lambda row: schid_state_maker(row['SCHID'], row['LEA_STATE']), axis = 1)

In [88]:
nces_for_missing_ny = nces_1516_full.copy()

nces_for_missing_ny['schid_state'] = nces_for_missing_ny.apply(lambda row: schid_state_maker(row['SCHID'], row['STABR']), axis = 1)

In [89]:
missing_ny_joined = schname_combined_missing_ny.set_index('schid_state').join(nces_for_missing_ny.reset_index().set_index('schid_state'), how = 'left', rsuffix = "_")

In [90]:
""" Join the missing NY schools with NCES """
missing_ny_joined[missing_ny_joined.LEVEL_.notnull()][['SCH_NAME','SCH_NAME_']]

,SCH_NAME,SCH_NAME_
schid_state,,
01348NY,is 187 the christa mcauliffe school,IS 187 CHRISTA MCAULIFFE SCHOOL (THE)
01409NY,"law, government and community service high school",LAW GOVERNMENT AND COMMUNITY SERVICE HIGH SCHOOL
02147NY,ps/ms 31 the william lloyd garrison,PS/MS 31 WILLIAM LLOYD GARRISON (THE)
02199NY,ps 45 horace e greene,PS/IS 45 HORACE E GREENE
02316NY,jhs 80 the mosholu parkway,JHS 80 MOSHOLU PARKWAY (THE)
02731NY,ps 225 the eileen e zaglin,PS 225 EILEEN E ZAGLIN (THE)
02829NY,ps 377 alejandina b de gautier,PS 377 ALEJANDRINA B DE GAUTIER
02961NY,"bronx school for law, government and justice",BRONX SCHOOL FOR LAW GOVERNMENT AND JUSTICE
03091NY,"high school of enterprise, business & technology",HIGH SCHOOL OF ENTERPRISE BUSINESS & TECHNOLOGY
04873NY,"new explorations into science,tech and math hi...",NEW EXPLORATIONS INTO SCIENCETECH AND MATH HIG...
04878NY,"is 318 math, science & tech through arts school",IS 318 MATH SCIENCE & TECH THROUGH ARTS SCHOOL
04888NY,"is 349 math, science and technology",IS 349 MATH SCIENCE AND TECHNOLOGY
05113NY,"high school for law, advocacy and community ju...",HIGH SCHOOL FOR LAW ADVOCACY AND COMMUNITY JUS...
05516NY,"science, tech & research high school at erasmus",SCIENCE TECH & RESEARCH HIGH SCHOOL AT ERASMUS
05521NY,ms 223 laboratory school of finance and techno...,MS 223 LABORATORY SCHOOL OF FINANCE AND TECHNO...
05536NY,"queens high school of teaching, liberal arts a...",QUEENS HIGH SCHOOL OF TEACHING LIBERAL ARTS AN...
05677NY,"marie curie high sch-nursing, medicine & appli...",MARIE CURIE HIGH SCH-NURSING MEDICINE & APPLIE...
05774NY,"high school for arts, imagination and inquiry",HIGH SCHOOL FOR ARTS IMAGINATION AND INQUIRY
05801NY,young scholars academy of the bronx,YOUNG SCHOLARS ACADEMY OF THE BRONX (THE)
05899NY,"high sch-construction, trades, engineering & a...",HIGH SCH-CONSTRUCTION TRADES ENGINEERING & ARC...
05962NY,"brooklyn community high sch-communication, art...",BROOKLYN COMMUNITY HIGH SCH-COMMUNICATION ARTS...
05985NY,"archimedes acad-math, sci, tech",ARCHIMEDES ACAD-MATH SCI TECH
05999NY,"queens high school for information, research a...",QUEENS HIGH SCHOOL FOR INFORMATION RESEARCH AN...
06105NY,high school for language and diplomacy,HIGH SCHOOL FOR LANGUAGE AND DIPLOMACY (THE)
06122NY,the brooklyn academy of global finance,BROOKLYN ACADEMY OF GLOBAL FINANCE (THE)
06148NY,urban assembly school for green careers,URBAN ASSEMBLY SCHOOL FOR GREEN CAREERS (THE)

In [91]:
""" Dealing with remaining missing NY Schools """
missing_ny_2 = missing_ny_joined.copy()
missing_ny_2 = missing_ny_2[missing_ny_2.LEVEL_.isnull()]

len(missing_ny_2.index)

10

In [92]:
missing_ny_2.columns.values

array(['COMBOKEY', 'LEA_STATE', 'LEA_STATE_NAME', 'LEAID', 'LEA_NAME',
       'SCHID', 'SCH_NAME', 'JJ', 'SCH_GRADE_PS', 'SCH_GRADE_KG',
       'SCH_GRADE_G01', 'SCH_GRADE_G02', 'SCH_GRADE_G03', 'SCH_GRADE_G04',
       'SCH_GRADE_G05', 'SCH_GRADE_G06', 'SCH_GRADE_G07', 'SCH_GRADE_G08',
       'SCH_GRADE_G09', 'SCH_GRADE_G10', 'SCH_GRADE_G11', 'SCH_GRADE_G12',
       'SCH_GRADE_UG', 'SCH_UGDETAIL_HS', 'SCH_STATUS_SPED',
       'SCH_STATUS_MAGNET', 'SCH_STATUS_CHARTER', 'SCH_STATUS_ALT',
       'SCH_ENR_HI_M', 'SCH_ENR_HI_F', 'SCH_ENR_AM_M', 'SCH_ENR_AM_F',
       'SCH_ENR_AS_M', 'SCH_ENR_AS_F', 'SCH_ENR_HP_M', 'SCH_ENR_HP_F',
       'SCH_ENR_BL_M', 'SCH_ENR_BL_F', 'SCH_ENR_WH_M', 'SCH_ENR_WH_F',
       'SCH_ENR_TR_M', 'SCH_ENR_TR_F', 'TOT_ENR_M', 'TOT_ENR_F',
       'SCH_ENR_LEP_M', 'SCH_ENR_LEP_F', 'SCH_ENR_IDEA_M',
       'SCH_ENR_IDEA_F', 'SCH_DUAL_IND', 'SCH_DUALENR_HI_M',
       'SCH_DUALENR_HI_F', 'SCH_DUALENR_AM_M', 'SCH_DUALENR_AM_F',
       'SCH_DUALENR_AS_M', 'SCH_DUALENR_AS_F', 'SCH_DUALENR_HP_M',
       'SCH_DUALENR_HP_F', 'SCH_DUALENR_BL_M', 'SCH_DUALENR_BL_F',
       'SCH_DUALENR_WH_M', 'SCH_DUALENR_WH_F', 'SCH_DUALENR_TR_M',
       'SCH_DUALENR_TR_F', 'TOT_DUALENR_M', 'TOT_DUALENR_F',
       'SCH_DUALENR_LEP_M', 'SCH_DUALENR_LEP_F', 'SCH_DUALENR_IDEA_M',
       'SCH_DUALENR_IDEA_F', 'SCH_APENR_IND', 'SCH_APENR_HI_M',
       'SCH_APENR_HI_F', 'SCH_APENR_AM_M', 'SCH_APENR_AM_F',
       'SCH_APENR_AS_M', 'SCH_APENR_AS_F', 'SCH_APENR_HP_M',
       'SCH_APENR_HP_F', 'SCH_APENR_BL_M', 'SCH_APENR_BL_F',
       'SCH_APENR_WH_M', 'SCH_APENR_WH_F', 'SCH_APENR_TR_M',
       'SCH_APENR_TR_F', 'TOT_APENR_M', 'TOT_APENR_F', 'SCH_APENR_LEP_M',
       'SCH_APENR_LEP_F', 'SCH_APENR_IDEA_M', 'SCH_APENR_IDEA_F',
       'SCH_IBENR_IND', 'SCH_IBENR_HI_M', 'SCH_IBENR_HI_F',
       'SCH_IBENR_AM_M', 'SCH_IBENR_AM_F', 'SCH_IBENR_AS_M',
       'SCH_IBENR_AS_F', 'SCH_IBENR_HP_M', 'SCH_IBENR_HP_F',
       'SCH_IBENR_BL_M', 'SCH_IBENR_BL_F', 'SCH_IBENR_WH_M',
       'SCH_IBENR_WH_F', 'SCH_IBENR_TR_M', 'SCH_IBENR_TR_F',
       'TOT_IBENR_M', 'TOT_IBENR_F', 'SCH_IBENR_LEP_M', 'SCH_IBENR_LEP_F',
       'SCH_IBENR_IDEA_M', 'SCH_IBENR_IDEA_F', 'TITLEI', 'STABR',
       'SCH_TYPE_TEXT', 'SCH_TYPE', 'LEVEL', 'VIRTUAL', 'GSLO', 'GSHI',
       'NMCNTY15', 'LOCALE15', 'LAT1516', 'LON1516', 'Low_Grade_Above9',
       'High_Grade_12', 'combokey', 'TITLEI_', 'LEAID_', 'LEA_NAME_',
       'STABR_', 'SCHID_', 'SCH_NAME_', 'SCH_TYPE_TEXT_', 'SCH_TYPE_',
       'LEVEL_', 'VIRTUAL_', 'GSLO_', 'GSHI_', 'NMCNTY15_', 'LOCALE15_',
       'LAT1516_', 'LON1516_'], dtype=object)

In [93]:
missing_ny_2 = missing_ny_2.drop(['TITLEI_', 'STABR_', 'SCH_TYPE_TEXT_', 'SCH_TYPE_',
                   'LEVEL_', 'VIRTUAL_', 'GSLO_', 'GSHI_', 
                   'NMCNTY15_', 'LOCALE15_', 'LAT1516_', 'LON1516_', 'combokey',
                   'LEAID_', 'LEA_NAME_', 'SCH_NAME_', 'SCHID_'], axis = 1)

In [94]:
missing_ny_2['actual_combokey'] = pd.Series(np.resize(0, len(missing_ny_2.index)), dtype = np.object)

missing_ny_2.at["99780NY", 'actual_combokey'] = "='360012306528'"
missing_ny_2.at["99796NY", 'actual_combokey'] = "='360012306535'"
missing_ny_2.at["99775NY", 'actual_combokey'] = "='360012006484'"
missing_ny_2.at["99776NY", 'actual_combokey'] = "='360010106508'"
missing_ny_2.at["99805NY", 'actual_combokey'] = "='360008306490'"
missing_ny_2.at["99874NY", 'actual_combokey'] = "='360007706372'"
missing_ny_2.at["99933NY", 'actual_combokey'] = "='360008106380'"
missing_ny_2.at["99968NY", 'actual_combokey'] = "='360007606296'"
missing_ny_2.at["99992NY", 'actual_combokey'] = "='360009706274'"
missing_ny_2.at["99995NY", 'actual_combokey'] = "='360009506273'"

In [95]:
""" Join again on the NCES """
missing_ny_2_joined = missing_ny_2.set_index('actual_combokey').join(nces_1516_full, how = 'left', rsuffix = '_')

In [96]:
"""How many matched?"""
len(missing_ny_2_joined[missing_ny_2_joined.LEVEL_.notnull()].index)

10

## Combine recovered schools and performing filters

** Concatenate the two recovered Missing NY Schools sets **

In [97]:
missing_ny_joined_matching = missing_ny_joined[missing_ny_joined.LEVEL_.notnull()]

In [98]:
all_missing_ny_recovered = missing_ny_2_joined.append(missing_ny_joined_matching)

**Join the original recovered schools (using schname_st identifier) with the recovered NY schools**

In [99]:
recovered_schools = schname_combined.copy()
recovered_schools = recovered_schools.fillna("Missing")

In [100]:
recovered_schools = recovered_schools[recovered_schools['SCH_NAME_'] != "Missing"]

In [101]:
recovered_schools_all = recovered_schools.append(all_missing_ny_recovered)

** Reformat the Columns ** -- Need to make sure that the recovered schools dataset's columns match the original filtered dataset's columns (required for concatenating the two sets properly)

In [102]:
"""Drop original nces columns (the ones with missing values)"""    
recovered_schools_all = recovered_schools_all.drop(['TITLEI', 'STABR', 'SCH_TYPE_TEXT', 'SCH_TYPE', 'LEVEL', 'VIRTUAL', 'GSLO', 'GSHI', 
                                            'NMCNTY15', 'LOCALE15', 'LAT1516', 'LON1516', 'combokey',
                                            'LEAID_', 'LEA_NAME_', 'SCH_NAME_', 'SCHID_'], axis = 1)
"""Rename new matching columns to replace the columns above (necessary for a proper concatenation later)"""
recovered_schools_all = recovered_schools_all.rename(lambda x: x.strip('_'), axis = 'columns')
recovered_schools_all = recovered_schools_all.set_index('COMBOKEY')

In [103]:
"""Do the columns between the original filtered set and recovered missing values set match"""
print(len(recovered_schools_all.columns.values))
print(len(filter5_crdc_nces_1516.columns.values))

124
124

In [104]:
""" How many schools recovered? """
len(recovered_schools_all.index)

857

** Non-Virtual Schools **

In [105]:
recovered_schools_filter1 = recovered_schools_all.copy()

In [106]:
recovered_schools_filter1 = recovered_schools_filter1[recovered_schools_filter1.VIRTUAL != 'Yes']

In [107]:
"""How many schools remain?"""
len(recovered_schools_filter1.index)

844

** NCES-Reported High Schools **

In [108]:
recovered_schools_filter2 = recovered_schools_filter1.copy()

In [109]:
recovered_schools_filter2 = recovered_schools_filter2[(recovered_schools_filter2.LEVEL == '3')]

In [110]:
"""How many schools remain?"""
len(recovered_schools_filter2.index)

508

** NCES-Reported Regular **

In [111]:
recovered_schools_filter3 = recovered_schools_filter2.copy()

In [112]:
recovered_schools_filter3 = recovered_schools_filter3[recovered_schools_filter3.SCH_TYPE == 1]

In [113]:
"""How many schools remain?"""
len(recovered_schools_filter3.index)

472

**Clean Duplicate Values **

In [114]:
recovered_schools_filter3.groupby('SCH_NAME')['SCH_NAME'].count().sort_values(ascending = False).head(4)

SCH_NAME
beacon high school                          2
university high                             2
performance learning center                 2
world academy for total community health    1
Name: SCH_NAME, dtype: int64

In [115]:
"""Dealing with Beacon"""
with pd.option_context('display.max_columns', 100):
    display(recovered_schools_filter3[recovered_schools_filter3.SCH_NAME.str.startswith('beacon')])

,GSHI,GSLO,High_Grade_12,JJ,LAT1516,LEAID,LEA_NAME,LEA_STATE,LEA_STATE_NAME,LEVEL,LOCALE15,LON1516,Low_Grade_Above9,NMCNTY15,SCHID,SCH_APENR_AM_F,SCH_APENR_AM_M,SCH_APENR_AS_F,SCH_APENR_AS_M,SCH_APENR_BL_F,SCH_APENR_BL_M,SCH_APENR_HI_F,SCH_APENR_HI_M,SCH_APENR_HP_F,SCH_APENR_HP_M,SCH_APENR_IDEA_F,SCH_APENR_IDEA_M,SCH_APENR_IND,SCH_APENR_LEP_F,SCH_APENR_LEP_M,SCH_APENR_TR_F,SCH_APENR_TR_M,SCH_APENR_WH_F,SCH_APENR_WH_M,SCH_DUALENR_AM_F,SCH_DUALENR_AM_M,SCH_DUALENR_AS_F,SCH_DUALENR_AS_M,SCH_DUALENR_BL_F,SCH_DUALENR_BL_M,SCH_DUALENR_HI_F,SCH_DUALENR_HI_M,SCH_DUALENR_HP_F,SCH_DUALENR_HP_M,SCH_DUALENR_IDEA_F,SCH_DUALENR_IDEA_M,SCH_DUALENR_LEP_F,SCH_DUALENR_LEP_M,SCH_DUALENR_TR_F,SCH_DUALENR_TR_M,...,SCH_GRADE_G04,SCH_GRADE_G05,SCH_GRADE_G06,SCH_GRADE_G07,SCH_GRADE_G08,SCH_GRADE_G09,SCH_GRADE_G10,SCH_GRADE_G11,SCH_GRADE_G12,SCH_GRADE_KG,SCH_GRADE_PS,SCH_GRADE_UG,SCH_IBENR_AM_F,SCH_IBENR_AM_M,SCH_IBENR_AS_F,SCH_IBENR_AS_M,SCH_IBENR_BL_F,SCH_IBENR_BL_M,SCH_IBENR_HI_F,SCH_IBENR_HI_M,SCH_IBENR_HP_F,SCH_IBENR_HP_M,SCH_IBENR_IDEA_F,SCH_IBENR_IDEA_M,SCH_IBENR_IND,SCH_IBENR_LEP_F,SCH_IBENR_LEP_M,SCH_IBENR_TR_F,SCH_IBENR_TR_M,SCH_IBENR_WH_F,SCH_IBENR_WH_M,SCH_NAME,SCH_STATUS_ALT,SCH_STATUS_CHARTER,SCH_STATUS_MAGNET,SCH_STATUS_SPED,SCH_TYPE,SCH_TYPE_TEXT,SCH_UGDETAIL_HS,STABR,TITLEI,TOT_APENR_F,TOT_APENR_M,TOT_DUALENR_F,TOT_DUALENR_M,TOT_ENR_F,TOT_ENR_M,TOT_IBENR_F,TOT_IBENR_M,VIRTUAL
COMBOKEY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
='362058000592',12,9,Yes,No,40.7612,3620580,NEW YORK CITY PUBLIC SCHOOLS,NY,NEW YORK,3,11,-73.9952,UG-Yes,New York County,592,0,0,17,5,11,5,32,14,0,0,2,2,Yes,0,0,0,2,65,32,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,Yes,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,beacon high school,No,No,No,No,1,Regular School,Yes,NY,No,125,58,-9,-9,839,466,-9,-9,No
='362058000592',12,9,Yes,No,41.5145,3620580,NEW YORK CITY PUBLIC SCHOOLS,NY,NEW YORK,3,21,-73.9635,UG-Yes,Dutchess County,592,0,0,17,5,11,5,32,14,0,0,2,2,Yes,0,0,0,2,65,32,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,Yes,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,beacon high school,No,No,No,No,1,Regular School,Yes,NY,No,125,58,-9,-9,839,466,-9,-9,No

In [116]:
filter5_crdc_nces_1516[filter5_crdc_nces_1516.SCH_NAME.str.startswith('BEACON')]

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,JJ,SCH_GRADE_PS,SCH_GRADE_KG,SCH_GRADE_G01,...,LEVEL,VIRTUAL,GSLO,GSHI,NMCNTY15,LOCALE15,LAT1516,LON1516,Low_Grade_Above9,High_Grade_12
COMBOKEY,,,,,,,,,,,,,,,,,,,,,
='360414000177',NY,NEW YORK,3604140,BEACON CITY SCHOOL DISTRICT,177,BEACON HIGH SCHOOL,No,No,No,No,...,3,No,9,12,Dutchess County,21,41.5145,-73.9635,UG-Yes,Yes
='362058000592',NY,NEW YORK,3620580,NEW YORK CITY PUBLIC SCHOOLS,592,BEACON HIGH SCHOOL,No,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,UG-Yes,Yes
='440000800297',RI,RHODE ISLAND,4400008,Beacon Charter School,297,BEACON Charter School,No,No,No,No,...,3,No,9,12,Providence County,21,42.0134,-71.502,Yes,Yes

In [117]:
"""Beacon High School in Dutchess County is already in the filter5 dataset -- Remove"""
recovered_schools_filter4 = recovered_schools_filter3.copy()
recovered_schools_filter4 = recovered_schools_filter4[(recovered_schools_filter4.SCH_NAME != 'beacon high school') | (recovered_schools_filter4.NMCNTY15 != 'Dutchess County')]

In [118]:
"""Dealing with Performance Learning Center"""
with pd.option_context('display.max_columns', 100):
    display(recovered_schools_filter3[recovered_schools_filter3.SCH_NAME.str.startswith('performance')])

,GSHI,GSLO,High_Grade_12,JJ,LAT1516,LEAID,LEA_NAME,LEA_STATE,LEA_STATE_NAME,LEVEL,LOCALE15,LON1516,Low_Grade_Above9,NMCNTY15,SCHID,SCH_APENR_AM_F,SCH_APENR_AM_M,SCH_APENR_AS_F,SCH_APENR_AS_M,SCH_APENR_BL_F,SCH_APENR_BL_M,SCH_APENR_HI_F,SCH_APENR_HI_M,SCH_APENR_HP_F,SCH_APENR_HP_M,SCH_APENR_IDEA_F,SCH_APENR_IDEA_M,SCH_APENR_IND,SCH_APENR_LEP_F,SCH_APENR_LEP_M,SCH_APENR_TR_F,SCH_APENR_TR_M,SCH_APENR_WH_F,SCH_APENR_WH_M,SCH_DUALENR_AM_F,SCH_DUALENR_AM_M,SCH_DUALENR_AS_F,SCH_DUALENR_AS_M,SCH_DUALENR_BL_F,SCH_DUALENR_BL_M,SCH_DUALENR_HI_F,SCH_DUALENR_HI_M,SCH_DUALENR_HP_F,SCH_DUALENR_HP_M,SCH_DUALENR_IDEA_F,SCH_DUALENR_IDEA_M,SCH_DUALENR_LEP_F,SCH_DUALENR_LEP_M,SCH_DUALENR_TR_F,SCH_DUALENR_TR_M,...,SCH_GRADE_G04,SCH_GRADE_G05,SCH_GRADE_G06,SCH_GRADE_G07,SCH_GRADE_G08,SCH_GRADE_G09,SCH_GRADE_G10,SCH_GRADE_G11,SCH_GRADE_G12,SCH_GRADE_KG,SCH_GRADE_PS,SCH_GRADE_UG,SCH_IBENR_AM_F,SCH_IBENR_AM_M,SCH_IBENR_AS_F,SCH_IBENR_AS_M,SCH_IBENR_BL_F,SCH_IBENR_BL_M,SCH_IBENR_HI_F,SCH_IBENR_HI_M,SCH_IBENR_HP_F,SCH_IBENR_HP_M,SCH_IBENR_IDEA_F,SCH_IBENR_IDEA_M,SCH_IBENR_IND,SCH_IBENR_LEP_F,SCH_IBENR_LEP_M,SCH_IBENR_TR_F,SCH_IBENR_TR_M,SCH_IBENR_WH_F,SCH_IBENR_WH_M,SCH_NAME,SCH_STATUS_ALT,SCH_STATUS_CHARTER,SCH_STATUS_MAGNET,SCH_STATUS_SPED,SCH_TYPE,SCH_TYPE_TEXT,SCH_UGDETAIL_HS,STABR,TITLEI,TOT_APENR_F,TOT_APENR_M,TOT_DUALENR_F,TOT_DUALENR_M,TOT_ENR_F,TOT_ENR_M,TOT_IBENR_F,TOT_IBENR_M,VIRTUAL
COMBOKEY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
='130129003727',12,9,Yes,No,33.4739,1301290,Cobb County,GA,GEORGIA,3,12,-81.9974,Yes,Richmond County,3727,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,No,No,No,No,No,No,Yes,Yes,Yes,No,No,No,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,performance learning center,No,No,No,No,1,Regular School,-9,GA,Yes,-9,-9,0,0,49,65,-9,-9,No
='130270003728',12,9,Yes,No,33.4739,1302700,Harris County,GA,GEORGIA,3,12,-81.9974,Yes,Richmond County,3728,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,0,0,0,0,2,5,2,0,0,0,0,0,0,0,2,0,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,performance learning center,No,No,No,No,1,Regular School,-9,GA,Yes,-9,-9,17,10,44,47,-9,-9,No

In [119]:
filter5_crdc_nces_1516[filter5_crdc_nces_1516.SCH_NAME.str.startswith('Performance')]

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,JJ,SCH_GRADE_PS,SCH_GRADE_KG,SCH_GRADE_G01,...,LEVEL,VIRTUAL,GSLO,GSHI,NMCNTY15,LOCALE15,LAT1516,LON1516,Low_Grade_Above9,High_Grade_12
COMBOKEY,,,,,,,,,,,,,,,,,,,,,
='130129003727',GA,GEORGIA,1301290,Cobb County,3727,Performance Learning Center,No,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Yes,Yes
='130270003728',GA,GEORGIA,1302700,Harris County,3728,Performance Learning Center,No,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Yes,Yes
='130438004221',GA,GEORGIA,1304380,Richmond County,4221,Performance Learning Center,No,No,No,No,...,3,No,9,12,Richmond County,12,33.4739,-81.9974,Yes,Yes
='370297002842',NC,NORTH CAROLINA,3702970,Charlotte-Mecklenburg Schools,2842,Performance Learning Center,No,No,No,No,...,3,No,9,12,Mecklenburg County,11,35.2951,-80.7957,Yes,Yes

In [120]:
"""Both of the performance learning centers here actually matched to a different 'performance learning center' record;
therefore, they should both be removed"""
recovered_schools_filter4 = recovered_schools_filter4[recovered_schools_filter4.SCH_NAME != 'performance learning center']

In [121]:
"""Dealing with university high"""
with pd.option_context('display.max_columns', 100):
    display(recovered_schools_filter3[recovered_schools_filter3.SCH_NAME.str.startswith('university high')])

,GSHI,GSLO,High_Grade_12,JJ,LAT1516,LEAID,LEA_NAME,LEA_STATE,LEA_STATE_NAME,LEVEL,LOCALE15,LON1516,Low_Grade_Above9,NMCNTY15,SCHID,SCH_APENR_AM_F,SCH_APENR_AM_M,SCH_APENR_AS_F,SCH_APENR_AS_M,SCH_APENR_BL_F,SCH_APENR_BL_M,SCH_APENR_HI_F,SCH_APENR_HI_M,SCH_APENR_HP_F,SCH_APENR_HP_M,SCH_APENR_IDEA_F,SCH_APENR_IDEA_M,SCH_APENR_IND,SCH_APENR_LEP_F,SCH_APENR_LEP_M,SCH_APENR_TR_F,SCH_APENR_TR_M,SCH_APENR_WH_F,SCH_APENR_WH_M,SCH_DUALENR_AM_F,SCH_DUALENR_AM_M,SCH_DUALENR_AS_F,SCH_DUALENR_AS_M,SCH_DUALENR_BL_F,SCH_DUALENR_BL_M,SCH_DUALENR_HI_F,SCH_DUALENR_HI_M,SCH_DUALENR_HP_F,SCH_DUALENR_HP_M,SCH_DUALENR_IDEA_F,SCH_DUALENR_IDEA_M,SCH_DUALENR_LEP_F,SCH_DUALENR_LEP_M,SCH_DUALENR_TR_F,SCH_DUALENR_TR_M,...,SCH_GRADE_G04,SCH_GRADE_G05,SCH_GRADE_G06,SCH_GRADE_G07,SCH_GRADE_G08,SCH_GRADE_G09,SCH_GRADE_G10,SCH_GRADE_G11,SCH_GRADE_G12,SCH_GRADE_KG,SCH_GRADE_PS,SCH_GRADE_UG,SCH_IBENR_AM_F,SCH_IBENR_AM_M,SCH_IBENR_AS_F,SCH_IBENR_AS_M,SCH_IBENR_BL_F,SCH_IBENR_BL_M,SCH_IBENR_HI_F,SCH_IBENR_HI_M,SCH_IBENR_HP_F,SCH_IBENR_HP_M,SCH_IBENR_IDEA_F,SCH_IBENR_IDEA_M,SCH_IBENR_IND,SCH_IBENR_LEP_F,SCH_IBENR_LEP_M,SCH_IBENR_TR_F,SCH_IBENR_TR_M,SCH_IBENR_WH_F,SCH_IBENR_WH_M,SCH_NAME,SCH_STATUS_ALT,SCH_STATUS_CHARTER,SCH_STATUS_MAGNET,SCH_STATUS_SPED,SCH_TYPE,SCH_TYPE_TEXT,SCH_UGDETAIL_HS,STABR,TITLEI,TOT_APENR_F,TOT_APENR_M,TOT_DUALENR_F,TOT_DUALENR_M,TOT_ENR_F,TOT_ENR_M,TOT_IBENR_F,TOT_IBENR_M,VIRTUAL
COMBOKEY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
='069902400001',12,9,Yes,No,36.8097,699024,University High School,CA,CALIFORNIA,3,11,-119.748,Yes,Fresno County,1,2,2,47,29,8,5,26,23,0,0,0,2,Yes,0,0,0,0,50,44,2,5,68,50,8,5,50,38,0,0,0,2,0,0,0,0,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,university high,No,Yes,No,No,1,Regular School,-9,CA,Missing,133,103,196,163,271,217,-9,-9,No
='069902400001',12,9,Yes,No,33.6513,699024,University High School,CA,CALIFORNIA,3,12,-117.823,Yes,Orange County,1,2,2,47,29,8,5,26,23,0,0,0,2,Yes,0,0,0,0,50,44,2,5,68,50,8,5,50,38,0,0,0,2,0,0,0,0,...,No,No,No,No,No,Yes,Yes,Yes,Yes,No,No,No,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,-9,No,-9,-9,-9,-9,-9,-9,university high,No,Yes,No,No,1,Regular School,-9,CA,Yes,133,103,196,163,271,217,-9,-9,No

In [122]:
filter5_crdc_nces_1516[filter5_crdc_nces_1516.SCH_NAME.str.startswith('University High')].head()

,LEA_STATE,LEA_STATE_NAME,LEAID,LEA_NAME,SCHID,SCH_NAME,JJ,SCH_GRADE_PS,SCH_GRADE_KG,SCH_GRADE_G01,...,LEVEL,VIRTUAL,GSLO,GSHI,NMCNTY15,LOCALE15,LAT1516,LON1516,Low_Grade_Above9,High_Grade_12
COMBOKEY,,,,,,,,,,,,,,,,,,,,,
='040852003206',AZ,ARIZONA,408520,Tolleson Union High School District,3206,University High School,No,No,No,No,...,3,No,9,12,Maricopa County,21,33.4484,-112.264,Yes,Yes
='040880001441',AZ,ARIZONA,408800,Tucson Unified District,1441,University High School,No,No,No,No,...,3,No,9,12,Pima County,11,32.2274,-110.89,Yes,Yes
='068450007067',CA,CALIFORNIA,684500,Irvine Unified,7067,University High,No,No,No,No,...,3,No,9,12,Orange County,12,33.6513,-117.823,Yes,Yes
='069902400001',CA,CALIFORNIA,699024,University High School,1,University High,No,No,No,No,...,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Missing,Yes,Yes
='090192001381',CT,CONNECTICUT,901920,HARTFORD SCHOOL DISTRICT,1381,University High of Science and Engineering,No,No,No,No,...,3,No,9,12,Hartford County,12,41.7979,-72.7097,Yes,Yes

In [123]:
"""The University High in Irvine was already accounted for; therefore, needs to be removed from the recovered"""
recovered_schools_filter4 = recovered_schools_filter4[(recovered_schools_filter4.SCH_NAME != 'university high') | (recovered_schools_filter4.NMCNTY15 != 'Orange County')]

In [124]:
'How many final recovered values?'
len(recovered_schools_filter4.index)

468

# <font color = green> VI. Concatenating Recovered Missing Values with the original Filtered Dataset </font>
<div class = 'alert alert-cell alert-info'> Finally, I concatenated the recovered high schools with the original filtered set.<br><br>

I ensured that no duplicate values were added in the process.

Then saved the file to "../filtered_data/04_filter_final.csv" </div>
<div class = 'alert alert-cell alert-warning'>
Final Total:  **15725 High Schools**

In [125]:
"""Remove the missing values"""
filter6_crdc_nces_1516 = filter5_crdc_nces_1516.copy()
filter6_crdc_nces_1516 = filter6_crdc_nces_1516[filter6_crdc_nces_1516.LEVEL != "Missing"]

In [126]:
"""How many initial Duplicates?
Interesting enough, these duplicates appear to legitimate; the problem seems to be that the schools actually have 
different names (e.g. "The ADAIR Co. High"'s are actually supposed to be labeled ADAIR Co. R-I High and ADAIR Co. R-II BRASHEAR)"""
filter6_crdc_nces_1516.groupby(['STABR','SCH_NAME','NMCNTY15'])['SCH_NAME'].count().sort_values(ascending=False).head()

STABR  SCH_NAME                    NMCNTY15
MO     ADAIR CO. HIGH              Adair County      2
TX     STERLING H S                Harris County     2
       TAYLOR H S                  Harris County     2
       LEE H S                     Harris County     2
WY     Wyoming Indian High School  Fremont County    1
Name: SCH_NAME, dtype: int64

In [127]:
recovered_schools_filter4.groupby(['STABR','SCH_NAME','NMCNTY15'])['SCH_NAME'].count().sort_values(ascending=False).head()

STABR  SCH_NAME                        NMCNTY15
TX     ischool high of hickory creek   Denton County    1
NY     bronx compass high school       Bronx County     1
       benjamin banneker academy       Kings County     1
       benjamin n cardozo high school  Queens County    1
       boys and girls high school      Kings County     1
Name: SCH_NAME, dtype: int64

In [128]:
# filtered_and_recovered = pd.concat([filter6_crdc_nces_1516, recovered_schools_filter4])
filtered_and_recovered = filter6_crdc_nces_1516.append(recovered_schools_filter4)

In [129]:
"""Do the numbers of columns match?"""
print(len(filter6_crdc_nces_1516.columns.values))
len(filtered_and_recovered.columns.values)

124

124

In [130]:
"""Because Columns are stored as dictionaries, there is no inherent order to the columns -- Pandas automatically 
uses an alphabetical sort on an append/concatenation.  I reorded the columns to show the SCH Name first"""
schName = ['SCH_NAME']
reorder = schName + [c for c in filtered_and_recovered.columns if c not in schName]
filtered_and_recovered = filtered_and_recovered[reorder]

In [131]:
"""No added duplicate records"""
filtered_and_recovered.groupby(['STABR','SCH_NAME','NMCNTY15'])['SCH_NAME'].count().sort_values(ascending=False).head()

STABR  SCH_NAME                    NMCNTY15
TX     STERLING H S                Harris County     2
MO     ADAIR CO. HIGH              Adair County      2
TX     TAYLOR H S                  Harris County     2
       LEE H S                     Harris County     2
WY     Wyoming Indian High School  Fremont County    1
Name: SCH_NAME, dtype: int64

In [132]:
"How many total high schools in the set?"
len(filtered_and_recovered.index)

15725

In [133]:
# filtered_and_recovered.to_csv('../filtered_data/04_filter_final.csv')

# Final Missing Schools
<div class = 'alert alert-cell alert-info'>**348 Schools**<br> Saved to '04_final_missing.csv'

In [134]:
final_missing = schname_combined[(schname_combined.SCH_NAME_.isnull()) & (schname_combined.LEA_NAME != 'NEW YORK CITY PUBLIC SCHOOLS')]

In [135]:
""" How many final missing schools? """
len(final_missing.index)

348

In [136]:
final_missing.to_csv('../filtered_data/04_final_missing.csv')

In [137]:
""" Top remaining unaccounted districts """
final_missing.groupby('LEA_NAME')['LEAID'].count().sort_values(ascending = False).head(10)

LEA_NAME
NORMAN                                                     9
Peters Township SD                                         6
Dept. of Svs. for Children Youth & Their Families          5
Boston                                                     4
OFFICE OF EDUCATION DEPARTMENT OF CHILDREN AND FAMILIES    4
WINDSOR SCHOOL DISTRICT                                    3
Cherokee County                                            3
NASSAU BOCES                                               3
ERIE 2-CHAUTAUQUA-CATTARAUGUS BOCES                        3
Geauga County Educational Service Center                   3
Name: LEAID, dtype: int64